[package]
name = "day10"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc-base = { path = "../../aoc-base" }
memoize = "0.5.1"
good_lp = { version = "1.14.2", features = ["highs"], default-features = false }
